version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: php7
    ports:
      - 8000:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: teste_laravel
      DB_USERNAME: root
      DB_PASSWORD: root
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: teste_laravel
      MYSQL_USER: app
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
